### ISSUE TITLE
GUI Blinking on Board update

### ISSUE THREAD

**Issue by mebegu** [awesome-comp302/chewy-lokum-legend-v2#10]
When game repaint the board on GUI, it is blinking.

**Comment by mebegu** [comment]
**Resolved!** I found out that the contents of board panel had been removing on every update. Because of that, it was showing an empty panel for a moment. I fixed it.

**Comment by TheVulch** [comment]
Should we fix the blinking problem with lokums that haven't been changed, though?

**Comment by mebegu** [comment]
All blinking problems are resolved. There is no more blinking anywhere. Check Pandora branch. We will directly use that branch for GUI.

**Comment by TheVulch** [comment]
Well...this is still an issue.
Doesn't need to be fixed, but it sure isn't fixed yet.

**Comment by mebegu** [comment]
It was a problem which was occurred because of default java graphics library. It won't be fixed.
